spring:
  application:
    name: "Pressure Tracker"
  datasource:
    host: "${TRACKER_DATABASE_HOST:localhost}"
    port: "${TRACKER_DATABASE_PORT:3306}"
    database: "${TRACKER_DATABASE_DATABASE:tracker}"
    username: "${TRACKER_DATABASE_USERNAME:root}"
    password: "${TRACKER_DATABASE_PASSWORD:toor}"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true